version: "3.9"
services:
  graphql:
    build: .
    image: "lidatong/aux-aptos-graphql"
    ports:
      - "4000:4000"
    depends_on:
      - fullnode
      - redis
  fullnode:
    build: mainnet
    image: "lidatong/fullnode"
    ports:
      - "8080:8080"
      - "9101:9101"
      - "6180:6180"
  #   volumes:
  #     - aptosmainnetfullnodeetc:/opt/aptos/etc
  #     - aptosmainnetfullnodedata:/opt/aptos/data
    working_dir: /opt/aptos/etc
    command: ["/usr/local/bin/aptos-node", "-f", "/opt/aptos/etc/fullnode.yaml"]
  redis:
    image: "redis:alpine"
