[package]
name = 'deployer'
version = '1.0.0'

[addresses]
AptosFramework = "0x1"
deployer = "_"

[dev-addresses]
deployer = "0x12345"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'aptos-cli-v0.3.9'
subdir = 'aptos-move/framework/aptos-framework'
